takeoff:
  init_x: 0.0
  init_y: 0.0
  init_z: 1.6
  hover_x: 0.5
  hover_y: 0.0
  hover_z: 5
  delay: 10 # unit: s

timeout:
  odom: 0.5 # unit: s
  cmd: 0.5 # unit: s

geometry_control:
  kpx: 7
  kpy: 7
  kpz: 7
  kvx: 2.5
  kvy: 2.5
  kvz: 2.5
  krx: 4
  kry: 4
  krz: 4
  hover_thrust_rate: 0.488

minJerk:
  v_max: 2
  yaw_dot_max: 0.5